<?php

########################################################################
# Extension Manager/Repository config file for ext: "simplequiz"
#
# Auto generated by Extbase Kickstarter 2010-03-13
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Quiz',
	'description' => 'A simple extension that provides a multiple choice quiz. Multiple correct answers are possible.',
	'category' => 'plugin',
	'author' => 'Susanne Moog',
	'author_email' => 's.moog@neusta.de',
	'author_company' => 'NEUSTA GmbH',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>